### Midterm Project
#### Yiscah Mark
#### nyc-rolling-sales data

##### I opened the file through a google drive link and printed the top few rows so I can examine the data and make changes.

In [1]:
import gdown
import pandas as pd

# The File ID extracted from your link
file_id = '1CgY9jjeGX8ZHSazqIqRBUfHkiNVLW0yj'
url = f'https://drive.google.com/uc?id={file_id}'

# Download the file
# This saves the file as 'midterm_data.csv' in your current folder
output = 'midterm_data.csv'
gdown.download(url, output, quiet=False)

# Open the dataset
df = pd.read_csv(output)

# Verify the requirements (Min 5 columns, 50 rows)
print(f"Dataset Shape: {df.shape}")
df.head()

Downloading...
From: https://drive.google.com/uc?id=1CgY9jjeGX8ZHSazqIqRBUfHkiNVLW0yj
To: /home/1bb32383-9cd3-4863-8b90-d3cb84c7db6b/midterm_data.csv
100%|██████████| 13.6M/13.6M [00:00<00:00, 96.4MB/s]

Dataset Shape: (84548, 22)

,Unnamed: 0,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
0,4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,392,6,,C2,153 AVENUE B,...,5,0,5,1633,6440,1900,2,C2,6625000,2017-07-19 00:00:00
1,5,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,26,,C7,234 EAST 4TH STREET,...,28,3,31,4616,18690,1900,2,C7,-,2016-12-14 00:00:00
2,6,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,39,,C7,197 EAST 3RD STREET,...,16,1,17,2212,7803,1900,2,C7,-,2016-12-09 00:00:00
3,7,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,402,21,,C4,154 EAST 7TH STREET,...,10,0,10,2272,6794,1913,2,C4,3936272,2016-09-23 00:00:00
4,8,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,404,55,,C2,301 EAST 10TH STREET,...,6,0,6,2369,4615,1900,2,C2,8000000,2016-11-17 00:00:00

##### I am printing general information about the data set including the data type of each column. There are 22 columns and 84,548 rows of data.

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84548 entries, 0 to 84547
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Unnamed: 0                      84548 non-null  int64
 1   BOROUGH                         84548 non-null  int64
 2   NEIGHBORHOOD                    84548 non-null  object
 3   BUILDING CLASS CATEGORY         84548 non-null  object
 4   TAX CLASS AT PRESENT            84548 non-null  object
 5   BLOCK                           84548 non-null  int64
 6   LOT                             84548 non-null  int64
 7   EASE-MENT                       84548 non-null  object
 8   BUILDING CLASS AT PRESENT       84548 non-null  object
 9   ADDRESS                         84548 non-null  object
 10  APARTMENT NUMBER                84548 non-null  object
 11  ZIP CODE                        84548 non-null  int64
 12  RESIDENTIAL UNITS               84548 non-null  int64
 13  COMMERCIAL UNITS                84548 non-null  int64
 14  TOTAL UNITS                     84548 non-null  int64
 15  LAND SQUARE FEET                84548 non-null  object
 16  GROSS SQUARE FEET               84548 non-null  object
 17  YEAR BUILT                      84548 non-null  int64
 18  TAX CLASS AT TIME OF SALE       84548 non-null  int64
 19  BUILDING CLASS AT TIME OF SALE  84548 non-null  object
 20  SALE PRICE                      84548 non-null  object
 21  SALE DATE                       84548 non-null  object
dtypes: int64(10), object(12)
memory usage: 14.2+ MB

##### The first thing I wanted to check for is spelling mistakes that often cause overlap of categories. By printing all unique values in each column across the set, I can see if anything is redundant due to a spelling mistake.

In [3]:
for col in df.columns:
    print(f"--- Unique values in '{col}' ---")
    print(df[col].unique())
    print("\n")

--- Unique values in 'Unnamed: 0' ---
[    4     5     6 ... 26737 26738 26739]


--- Unique values in 'BOROUGH' ---
[1 2 3 4 5]


--- Unique values in 'NEIGHBORHOOD' ---
['ALPHABET CITY' 'CHELSEA' 'CHINATOWN' 'CIVIC CENTER' 'CLINTON'
 'EAST VILLAGE' 'FASHION' 'FINANCIAL' 'FLATIRON' 'GRAMERCY'
 'GREENWICH VILLAGE-CENTRAL' 'GREENWICH VILLAGE-WEST' 'HARLEM-CENTRAL'
 'HARLEM-EAST' 'HARLEM-UPPER' 'HARLEM-WEST' 'INWOOD' 'JAVITS CENTER'
 'KIPS BAY' 'LITTLE ITALY' 'LOWER EAST SIDE' 'MANHATTAN VALLEY'
 'MIDTOWN CBD' 'MIDTOWN EAST' 'MIDTOWN WEST' 'MORNINGSIDE HEIGHTS'
 'MURRAY HILL' 'ROOSEVELT ISLAND' 'SOHO' 'SOUTHBRIDGE' 'TRIBECA'
 'UPPER EAST SIDE (59-79)' 'UPPER EAST SIDE (79-96)'
 'UPPER EAST SIDE (96-110)' 'UPPER WEST SIDE (59-79)'
 'UPPER WEST SIDE (79-96)' 'UPPER WEST SIDE (96-116)'
 'WASHINGTON HEIGHTS LOWER' 'WASHINGTON HEIGHTS UPPER' 'BATHGATE'
 'BAYCHESTER' 'BEDFORD PARK/NORWOOD' 'BELMONT' 'BRONX PARK' 'BRONXDALE'
 'CASTLE HILL/UNIONPORT' 'CITY ISLAND' 'CITY ISLAND-PELHAM STRIP'
 'CO-OP CITY' 'COUNTRY CLUB' 'CROTONA PARK' 'EAST RIVER' 'EAST TREMONT'
 'FIELDSTON' 'FORDHAM' 'HIGHBRIDGE/MORRIS HEIGHTS' 'HUNTS POINT'
 'KINGSBRIDGE HTS/UNIV HTS' 'KINGSBRIDGE/JEROME PARK' 'MELROSE/CONCOURSE'
 'MORRIS PARK/VAN NEST' 'MORRISANIA/LONGWOOD' 'MOTT HAVEN/PORT MORRIS'
 'MOUNT HOPE/MOUNT EDEN' 'PARKCHESTER' 'PELHAM BAY' 'PELHAM GARDENS'
 'PELHAM PARKWAY NORTH' 'PELHAM PARKWAY SOUTH' 'RIVERDALE'
 'SCHUYLERVILLE/PELHAM BAY' 'SOUNDVIEW' 'THROGS NECK' 'VAN CORTLANDT PARK'
 'WAKEFIELD' 'WESTCHESTER' 'WILLIAMSBRIDGE' 'WOODLAWN' 'BATH BEACH'
 'BAY RIDGE' 'BEDFORD STUYVESANT' 'BENSONHURST' 'BERGEN BEACH'
 'BOERUM HILL' 'BOROUGH PARK' 'BRIGHTON BEACH' 'BROOKLYN HEIGHTS'
 'BROWNSVILLE' 'BUSH TERMINAL' 'BUSHWICK' 'CANARSIE' 'CARROLL GARDENS'
 'CLINTON HILL' 'COBBLE HILL' 'COBBLE HILL-WEST' 'CONEY ISLAND'
 'CROWN HEIGHTS' 'CYPRESS HILLS' 'DOWNTOWN-FULTON FERRY'
 'DOWNTOWN-FULTON MALL' 'DOWNTOWN-METROTECH' 'DYKER HEIGHTS'
 'EAST NEW YORK' 'FLATBUSH-CENTRAL' 'FLATBUSH-EAST'
 'FLATBUSH-LEFFERTS GARDEN' 'FLATBUSH-NORTH' 'FLATLANDS' 'FORT GREENE'
 'GERRITSEN BEACH' 'GOWANUS' 'GRAVESEND' 'GREENPOINT' 'JAMAICA BAY'
 'KENSINGTON' 'MADISON' 'MANHATTAN BEACH' 'MARINE PARK' 'MIDWOOD'
 'MILL BASIN' 'NAVY YARD' 'OCEAN HILL' 'OCEAN PARKWAY-NORTH'
 'OCEAN PARKWAY-SOUTH' 'OLD MILL BASIN' 'PARK SLOPE' 'PARK SLOPE SOUTH'
 'PROSPECT HEIGHTS' 'RED HOOK' 'SEAGATE' 'SHEEPSHEAD BAY' 'SPRING CREEK'
 'SUNSET PARK' 'WILLIAMSBURG-CENTRAL' 'WILLIAMSBURG-EAST'
 'WILLIAMSBURG-NORTH' 'WILLIAMSBURG-SOUTH' 'WINDSOR TERRACE'
 'WYCKOFF HEIGHTS' 'AIRPORT LA GUARDIA' 'ARVERNE' 'ASTORIA' 'BAYSIDE'
 'BEECHHURST' 'BELLE HARBOR' 'BELLEROSE' 'BRIARWOOD' 'BROAD CHANNEL'
 'CAMBRIA HEIGHTS' 'COLLEGE POINT' 'CORONA' 'DOUGLASTON' 'EAST ELMHURST'
 'ELMHURST' 'FAR ROCKAWAY' 'FLORAL PARK' 'FLUSHING MEADOW PARK'
 'FLUSHING-NORTH' 'FLUSHING-SOUTH' 'FOREST HILLS' 'FRESH MEADOWS'
 'GLEN OAKS' 'GLENDALE' 'HAMMELS' 'HILLCREST' 'HOLLIS' 'HOLLIS HILLS'
 'HOLLISWOOD' 'HOWARD BEACH' 'JACKSON HEIGHTS' 'JAMAICA' 'JAMAICA ESTATES'
 'JAMAICA HILLS' 'KEW GARDENS' 'LAURELTON' 'LITTLE NECK'
 'LONG ISLAND CITY' 'MASPETH' 'MIDDLE VILLAGE' 'NEPONSIT'
 'OAKLAND GARDENS' 'OZONE PARK' 'QUEENS VILLAGE' 'REGO PARK'
 'RICHMOND HILL' 'RIDGEWOOD' 'ROCKAWAY PARK' 'ROSEDALE'
 'SO. JAMAICA-BAISLEY PARK' 'SOUTH JAMAICA' 'SOUTH OZONE PARK'
 'SPRINGFIELD GARDENS' 'ST. ALBANS' 'SUNNYSIDE' 'WHITESTONE' 'WOODHAVEN'
 'WOODSIDE' 'ANNADALE' 'ARDEN HEIGHTS' 'ARROCHAR' 'ARROCHAR-SHORE ACRES'
 'BLOOMFIELD' 'BULLS HEAD' 'CASTLETON CORNERS' 'CLOVE LAKES' 'CONCORD'
 'CONCORD-FOX HILLS' 'DONGAN HILLS' 'DONGAN HILLS-COLONY'
 'DONGAN HILLS-OLD TOWN' 'ELTINGVILLE' 'EMERSON HILL' 'FRESH KILLS'
 'GRANT CITY' 'GRASMERE' 'GREAT KILLS' 'GREAT KILLS-BAY TERRACE'
 'GRYMES HILL' 'HUGUENOT' 'LIVINGSTON' 'MANOR HEIGHTS' 'MARINERS HARBOR'
 'MIDLAND BEACH' 'NEW BRIGHTON' 'NEW BRIGHTON-ST. GEORGE' 'NEW DORP'
 'NEW DORP-BEACH' 'NEW DORP-HEIGHTS' 'NEW SPRINGVILLE' 'OAKWOOD'
 'OAKWOOD-BEACH' 'PLEASANT PLAINS' 'PORT IVORY' 'PORT RICHMOND'
 'PRINCES BAY' 'RICHMONDTOWN' 'RICHMONDTOWN-LIGHTHS HILL' 'ROSEBANK'
 'ROSSVILLE' 'ROSSVILLE-CHARLESTON' 'ROSSVILLE-PORT MOBIL'
 'ROSSVILLE-RICHMOND VALLEY' 'SILVER LAKE' 'SOUTH BEACH' 'STAPLETON'
 'STAPLETON-CLIFTON' 'TODT HILL' 'TOMPKINSVILLE' 'TOTTENVILLE' 'TRAVIS'
 'WEST NEW BRIGHTON' 'WESTERLEIGH' 'WILLOWBROOK' 'WOODROW']


--- Unique values in 'BUILDING CLASS CATEGORY' ---
['07 RENTALS - WALKUP APARTMENTS             '
 '08 RENTALS - ELEVATOR APARTMENTS           '
 '09 COOPS - WALKUP APARTMENTS               '
 '10 COOPS - ELEVATOR APARTMENTS             '
 '11A CONDO-RENTALS                           '
 '12 CONDOS - WALKUP APARTMENTS              '
 '13 CONDOS - ELEVATOR APARTMENTS            '
 '14 RENTALS - 4-10 UNIT                     '
 '15 CONDOS - 2-10 UNIT RESIDENTIAL          '
 '16 CONDOS - 2-10 UNIT WITH COMMERCIAL UNIT '
 '17 CONDO COOPS                             '
 '22 STORE BUILDINGS                         '
 '37 RELIGIOUS FACILITIES                    '
 '42 CONDO CULTURAL/MEDICAL/EDUCATIONAL/ETC  '
 '46 CONDO STORE BUILDINGS                   '
 '47 CONDO NON-BUSINESS STORAGE              '
 '01 ONE FAMILY DWELLINGS                    '
 '02 TWO FAMILY DWELLINGS                    '
 '03 THREE FAMILY DWELLINGS                  '
 '04 TAX CLASS 1 CONDOS                      '
 '21 OFFICE BUILDINGS                        '
 '23 LOFT BUILDINGS                          '
 '25 LUXURY HOTELS                           '
 '26 OTHER HOTELS                            '
 '28 COMMERCIAL CONDOS                       '
 '29 COMMERCIAL GARAGES                      '
 '35 INDOOR PUBLIC AND CULTURAL FACILITIES   '
 '38 ASYLUMS AND HOMES                       '
 '43 CONDO OFFICE BUILDINGS                  '
 '44 CONDO PARKING                           '
 '48 CONDO TERRACES/GARDENS/CABANAS          '
 '31 COMMERCIAL VACANT LAND                  '
 '32 HOSPITAL AND HEALTH FACILITIES          '
 '41 TAX CLASS 4 - OTHER                     '
 '18 TAX CLASS 3 - UNTILITY PROPERTIES       '
 '30 WAREHOUSES                              '
 '36 OUTDOOR RECREATIONAL FACILITIES         '
 '49 CONDO WAREHOUSES/FACTORY/INDUS          '
 '34 THEATRES                                '
 '27 FACTORIES                               '
 '40 SELECTED GOVERNMENTAL FACILITIES        '
 '45 CONDO HOTELS                            '
 '33 EDUCATIONAL FACILITIES                  '
 '11 SPECIAL CONDO BILLING LOTS              '
 '05 TAX CLASS 1 VACANT LAND                 '
 '06 TAX CLASS 1 - OTHER                     '
 '39 TRANSPORTATION FACILITIES               ']


--- Unique values in 'TAX CLASS AT PRESENT' ---
['2A' '2' '2B' '2C' ' ' '4' '1' '1C' '3' '1A' '1B']


--- Unique values in 'BLOCK' ---
[ 392  399  402 ... 6918 7074 7092]


--- Unique values in 'LOT' ---
[  6  26  39 ... 655 423 679]


--- Unique values in 'EASE-MENT' ---
[' ']


--- Unique values in 'BUILDING CLASS AT PRESENT' ---
['C2' 'C7' 'C4' 'D5' 'D9' 'D7' 'D1' 'C6' 'D0' 'D4' 'RR' ' ' 'R2' 'R4' 'S3'
 'S4' 'S5' 'R1' 'R8' 'R9' 'K4' 'M9' 'M3' 'RK' 'RS' 'A9' 'A4' 'B3' 'B1'
 'S2' 'C0' 'R6' 'C5' 'C3' 'C1' 'D6' 'S9' 'O2' 'O1' 'O3' 'O5' 'O6' 'K1'
 'K2' 'L9' 'L8' 'L1' 'H1' 'H8' 'H3' 'R5' 'G6' 'P7' 'M1' 'N2' 'RB' 'RG'
 'RT' 'K9' 'V1' 'GW' 'G2' 'I7' 'M4' 'Z9' 'B9' 'D3' 'G9' 'I9' 'U6' 'O4'
 'L3' 'H2' 'E1' 'Z3' 'RW' 'C9' 'J5' 'N9' 'S1' 'A5' 'J8' 'B2' 'C8' 'F5'
 'Q1' 'G7' 'G5' 'G4' 'P2' 'Q9' 'Y1' 'RA' 'RP' 'O8' 'HR' 'G1' 'E7' 'I5'
 'R3' 'I4' 'H9' 'RH' 'D8' 'HB' 'J4' 'W2' 'P9' 'A7' 'D2' 'S0' 'O7' 'O9'
 'W3' 'HS' 'H6' 'J9' 'R0' 'HH' 'W8' 'W6' 'A1' 'K5' 'F1' 'V9' 'A2' 'V0'
 'G0' 'F4' 'E9' 'I3' 'W4' 'V3' 'I1' 'A6' 'Q8' 'A3' 'Z0' 'W1' 'U1' 'F2'
 'F9' 'GU' 'I6' 'G8' 'P5' 'Y3' 'W9' 'M2' 'G3' 'V6' 'K7' 'K3' 'R7' 'P8'
 'K6' 'V2' 'E2' 'Z2' 'T2' 'K8' 'P6' 'A0' 'H4' 'J1' 'CM' 'Z7']


--- Unique values in 'ADDRESS' ---
['153 AVENUE B' '234 EAST 4TH   STREET' '197 EAST 3RD   STREET' ...
 '49 PITNEY AVENUE' '2730 ARTHUR KILL ROAD' '155 CLAY PIT ROAD']


--- Unique values in 'APARTMENT NUMBER' ---
[' ' 'RES' 'UNIT1' ... '115' 'MS-B' '363']


--- Unique values in 'ZIP CODE' ---
[10009     0 10002 10011 10001 10014 10010 10013 10038 10007 10036 10019
 10018 10003 10005 10004 10006 10016 10012 10026 10030 10031 10027 10035
 10037 10029 10039 10032 10128 10463 10034 10025 10022 10017 10167 10023
 10105 10033 10044 10280 10282 10281 10065 10021 10075 10028 10024 10069
 10040 10457 10458 10451 10456 10469 10466 10475 10468 10467 10460 10473
 10472 10464 10462 10803 10465 10459 10471 10453 10452 10454 10474 10455
 10461 10470 11228 11214 11220 11209 11219 11221 11233 11213 11206 11216
 11205 11238 11226 11204 11234 11217 11201 11218 11232 11230 11235 11212
 11237 11207 11236 11239 11231 11249 11224 11225 11208 11210 11203 11229
 11215 11223 11222 11211 11370 11691 11692 11102 11106 11103 11377 11105
 11101 11361 11360 11357 11358 11364 11693 11694 11426 11428 11004 11001
 11435 11411 11356 11354 11420 11368 11373 11372 11363 11362 11369 11378
 11040 11375 11355 11365 11367 11366 11374 11385 11005 11421 11379 11432
 11423 11412 11427 11429 11433 11414 11422 11415 11418 11413 11109 11104
 11416 11417 11419 11436 11434 11430 10312 10305 10314 10303 10310 10302
 10301 10304 10306 10308 10309 10307]


--- Unique values in 'RESIDENTIAL UNITS' ---
[   5   28   16   10    6   20    8   44   15   24   30    0   47  132
    1    3    4    2   22    9  210   35   17   11    7   18   27   14
   12   21   40   19   48   79   55  529  476  317   42   23   25  107
  133   31   36   34   33   90   74   29   13  286  256  771  257   38
  311   41   51   76   54   45   72   56   68   37   50   26   61   60
  894   67  550  184   78  181   86  259  102  233  121   52 1641   96
   87  100  113   99   92   70  369   77  232  315   91   32   66   64
  109  387  153   59  193   62  103  146  287   94   46   84   75   65
   95   49   63   43  716  680  179   71   39   53  283  114   89   73
   83  498   81  162  127  222  130   58  159  462  142  948  129  889
  271  150  120   57  117  106   85  118  164  139  165  122  134  278
  135  324  180  405  136  168  144  152  138   88  244  291 1844  198
  148  175  296  446  420  335  143  128]


--- Unique values in 'COMMERCIAL UNITS' ---
[   0    3    1    2    4   13    5   24    6   19   10   15   14    8
    7   35   42   55   17   38   12   27  422    9   23   52  318   20
   67   11  254   26   49   30   91   59   62   31   73   56   34   32
   18   22   28  147  184   25  172  436   16 2261   51   21  126]


--- Unique values in 'TOTAL UNITS' ---
[   5   31   17   10    6   20    8   46   15   24   34    0   47  132
    1    4    2    3    7    9   16  211   32   13   19   35   18   14
   30   12   21   23   45   26   11   48   82   55   42   38   27  422
  538  482  323   52  318   67   25   22   28  107  137   36   37   96
  138   76   33  286  256  771  257   44  315   41   51   40   29   81
   54   72   56   68   74   39   50   61  902   70  551  254  185   78
  181   49   91   87  269  102  234  235  233   59   62   73   43  121
 1653  192  100  113   99   92   75  374   77  238  317   93   69   60
   64  111  395  155  193  103  146  287   94   84   65   95   63   71
   57  736  680  179   53  291   66  114   79   83  520  163  127  222
  130   90   58  159  462  142  955  129  889  109  147  271  150  120
  117  106   86  118  164  139  165  122  279  135  324  180  184  104
  405  136  168  172  436  145  152  140   89  148  244  295 1866  278
  198 2261  176  296  446  420  336  143  126  128]


--- Unique values in 'LAND SQUARE FEET' ---
['1633' '4616' '2212' ... '11088' '208033' '10796']


--- Unique values in 'GROSS SQUARE FEET' ---
['6440' '18690' '7803' ... '977' '2683' '64117']


--- Unique values in 'YEAR BUILT' ---
[1900 1913 1920 1910 2009 1925 1902 1928 1930 1935 1937 1915 1950 1929
 1901 1940 2005    0 1989 2014 2008 1965 2013 2003 2006 2007 1951 1899
 1850 1905 1864 1917 1911 1983 1926 1963 1960 1889 1898 1939 1938 1927
 1909 1958 1904 1907 1987 1931 1984 1948 2004 1918 1875 2012 1973 2011
 1922 2001 1932 1980 1908 1953 1906 2015 1946 1921 2010 1954 1111 1924
 1990 1890 1991 1988 1895 2016 1957 1986 1966 1998 1870 1923 1969 2017
 1968 1934 1956 1982 1914 1903 1967 1840 1912 1964 1955 1961 1851 2000
 1959 1962 1945 1972 1976 1916 1880 1970 1846 1941 1952 1896 1985 1981
 1888 1947 1975 1974 2002 1994 1892 1894 1891 1996 1997 1949 1999 1800
 1979 1971 1977 1942 1978 1826 1881 1919 1883 1936 1993 1995 1933 1992
 1943 1944 1847 1829 1844 1835 1852 1856 1854 1832 1845 1849 1855 1871
 1893 1865 1882 1680]


--- Unique values in 'TAX CLASS AT TIME OF SALE' ---
[2 4 1 3]


--- Unique values in 'BUILDING CLASS AT TIME OF SALE' ---
['C2' 'C7' 'C4' 'D5' 'D9' 'D7' 'D1' 'C6' 'D0' 'D4' 'RR' 'R2' 'R4' 'S3'
 'S4' 'S5' 'R1' 'R8' 'R9' 'K4' 'M9' 'M3' 'RA' 'RK' 'RS' 'A9' 'A4' 'B3'
 'B1' 'S2' 'C0' 'R6' 'C5' 'C3' 'C1' 'D6' 'S9' 'O2' 'O1' 'O3' 'O5' 'O6'
 'K1' 'K2' 'L9' 'L8' 'L1' 'H1' 'H8' 'H3' 'R5' 'G9' 'G6' 'P7' 'M1' 'N2'
 'RB' 'RG' 'RT' 'K9' 'V1' 'GW' 'G2' 'I7' 'M4' 'Z9' 'B9' 'D3' 'I9' 'U6'
 'O4' 'L3' 'H2' 'E1' 'Z3' 'Q1' 'RW' 'C9' 'J5' 'N9' 'S1' 'A5' 'J8' 'B2'
 'C8' 'F5' 'G7' 'G5' 'G4' 'P2' 'Q9' 'Y1' 'RP' 'O8' 'HR' 'G1' 'E7' 'I5'
 'R3' 'I4' 'H9' 'RH' 'D8' 'HB' 'J4' 'W2' 'P9' 'A7' 'D2' 'S0' 'O7' 'O9'
 'W3' 'HS' 'H6' 'J9' 'R0' 'HH' 'W8' 'W6' 'A1' 'K5' 'F1' 'V9' 'A2' 'V0'
 'G0' 'F4' 'E9' 'I3' 'W4' 'V3' 'I1' 'A6' 'Q8' 'A3' 'Z0' 'W1' 'U1' 'F2'
 'F9' 'GU' 'I6' 'G8' 'P5' 'Y3' 'W9' 'M2' 'G3' 'V6' 'K7' 'K3' 'H4' 'R7'
 'P8' 'K6' 'V2' 'E2' 'Z2' 'T2' 'K8' 'P6' 'A0' 'J1' 'CM' 'Z7']


--- Unique values in 'SALE PRICE' ---
['6625000' ' -  ' '3936272' ... '408092' '11693337' '69300']


--- Unique values in 'SALE DATE' ---
['2017-07-19 00:00:00' '2016-12-14 00:00:00' '2016-12-09 00:00:00'
 '2016-09-23 00:00:00' '2016-11-17 00:00:00' '2017-07-20 00:00:00'
 '2017-06-20 00:00:00' '2016-11-07 00:00:00' '2016-10-17 00:00:00'
 '2016-09-06 00:00:00' '2017-03-10 00:00:00' '2017-04-28 00:00:00'
 '2017-06-09 00:00:00' '2017-07-14 00:00:00' '2017-03-16 00:00:00'
 '2016-09-01 00:00:00' '2017-08-17 00:00:00' '2016-09-07 00:00:00'
 '2017-08-30 00:00:00' '2017-06-21 00:00:00' '2017-01-30 00:00:00'
 '2017-07-07 00:00:00' '2017-08-04 00:00:00' '2017-01-09 00:00:00'
 '2017-04-18 00:00:00' '2017-06-19 00:00:00' '2017-08-28 00:00:00'
 '2017-05-10 00:00:00' '2016-12-02 00:00:00' '2017-01-31 00:00:00'
 '2017-06-28 00:00:00' '2016-12-07 00:00:00' '2017-08-24 00:00:00'
 '2017-06-27 00:00:00' '2017-03-17 00:00:00' '2017-06-14 00:00:00'
 '2017-01-17 00:00:00' '2017-01-11 00:00:00' '2017-04-21 00:00:00'
 '2017-06-29 00:00:00' '2016-10-05 00:00:00' '2017-02-02 00:00:00'
 '2017-03-20 00:00:00' '2017-04-13 00:00:00' '2017-06-06 00:00:00'
 '2017-07-17 00:00:00' '2016-12-06 00:00:00' '2017-07-13 00:00:00'
 '2017-05-17 00:00:00' '2017-05-31 00:00:00' '2017-07-12 00:00:00'
 '2017-01-19 00:00:00' '2017-05-03 00:00:00' '2016-09-29 00:00:00'
 '2017-08-07 00:00:00' '2017-01-20 00:00:00' '2017-02-23 00:00:00'
 '2016-09-12 00:00:00' '2017-08-09 00:00:00' '2017-04-07 00:00:00'
 '2017-05-11 00:00:00' '2016-10-13 00:00:00' '2016-10-19 00:00:00'
 '2016-12-30 00:00:00' '2017-02-24 00:00:00' '2016-09-21 00:00:00'
 '2016-11-03 00:00:00' '2017-03-31 00:00:00' '2017-05-25 00:00:00'
 '2017-02-14 00:00:00' '2017-02-01 00:00:00' '2017-05-08 00:00:00'
 '2017-08-14 00:00:00' '2017-06-23 00:00:00' '2017-03-27 00:00:00'
 '2017-04-22 00:00:00' '2017-07-06 00:00:00' '2017-06-12 00:00:00'
 '2017-06-22 00:00:00' '2017-02-17 00:00:00' '2016-09-08 00:00:00'
 '2016-12-23 00:00:00' '2017-07-24 00:00:00' '2016-10-08 00:00:00'
 '2016-12-08 00:00:00' '2017-04-25 00:00:00' '2016-12-13 00:00:00'
 '2017-01-12 00:00:00' '2017-03-03 00:00:00' '2017-01-25 00:00:00'
 '2016-12-19 00:00:00' '2016-12-16 00:00:00' '2016-12-29 00:00:00'
 '2017-01-13 00:00:00' '2016-12-21 00:00:00' '2017-03-30 00:00:00'
 '2017-04-14 00:00:00' '2017-05-22 00:00:00' '2017-05-19 00:00:00'
 '2017-02-08 00:00:00' '2016-11-08 00:00:00' '2017-03-02 00:00:00'
 '2017-01-05 00:00:00' '2016-10-11 00:00:00' '2016-11-15 00:00:00'
 '2017-04-03 00:00:00' '2016-11-28 00:00:00' '2016-11-14 00:00:00'
 '2017-04-20 00:00:00' '2017-05-05 00:00:00' '2016-11-16 00:00:00'
 '2017-07-18 00:00:00' '2017-05-15 00:00:00' '2017-07-31 00:00:00'
 '2017-06-07 00:00:00' '2016-11-02 00:00:00' '2017-04-19 00:00:00'
 '2017-07-11 00:00:00' '2016-09-28 00:00:00' '2017-01-06 00:00:00'
 '2016-10-20 00:00:00' '2017-03-28 00:00:00' '2017-04-17 00:00:00'
 '2016-10-26 00:00:00' '2017-02-06 00:00:00' '2017-03-23 00:00:00'
 '2017-08-31 00:00:00' '2017-07-27 00:00:00' '2016-11-10 00:00:00'
 '2016-10-28 00:00:00' '2016-12-05 00:00:00' '2016-11-29 00:00:00'
 '2016-11-21 00:00:00' '2017-01-27 00:00:00' '2016-09-26 00:00:00'
 '2017-02-21 00:00:00' '2016-10-06 00:00:00' '2017-08-25 00:00:00'
 '2016-11-30 00:00:00' '2017-02-16 00:00:00' '2017-03-01 00:00:00'
 '2016-10-31 00:00:00' '2016-12-20 00:00:00' '2016-11-18 00:00:00'
 '2017-04-10 00:00:00' '2016-11-23 00:00:00' '2016-12-27 00:00:00'
 '2017-05-12 00:00:00' '2017-02-15 00:00:00' '2017-07-10 00:00:00'
 '2017-03-06 00:00:00' '2017-06-30 00:00:00' '2017-07-26 00:00:00'
 '2017-03-22 00:00:00' '2017-03-08 00:00:00' '2016-09-14 00:00:00'
 '2017-04-26 00:00:00' '2016-09-27 00:00:00' '2017-04-27 00:00:00'
 '2016-12-01 00:00:00' '2017-01-23 00:00:00' '2016-11-04 00:00:00'
 '2016-10-07 00:00:00' '2017-06-05 00:00:00' '2017-05-23 00:00:00'
 '2017-01-26 00:00:00' '2016-12-28 00:00:00' '2017-05-02 00:00:00'
 '2017-03-07 00:00:00' '2017-05-01 00:00:00' '2016-10-14 00:00:00'
 '2016-12-15 00:00:00' '2016-11-01 00:00:00' '2016-09-15 00:00:00'
 '2016-10-01 00:00:00' '2016-10-24 00:00:00' '2016-11-11 00:00:00'
 '2017-02-09 00:00:00' '2017-07-25 00:00:00' '2017-03-15 00:00:00'
 '2016-09-16 00:00:00' '2017-03-29 00:00:00' '2017-06-26 00:00:00'
 '2016-10-18 00:00:00' '2016-12-22 00:00:00' '2016-09-09 00:00:00'
 '2016-11-09 00:00:00' '2017-05-04 00:00:00' '2017-06-13 00:00:00'
 '2017-02-10 00:00:00' '2017-04-24 00:00:00' '2017-05-24 00:00:00'
 '2017-02-28 00:00:00' '2017-04-11 00:00:00' '2016-10-25 00:00:00'
 '2017-08-21 00:00:00' '2017-08-29 00:00:00' '2017-08-01 00:00:00'
 '2017-06-08 00:00:00' '2017-08-23 00:00:00' '2016-10-27 00:00:00'
 '2017-06-02 00:00:00' '2017-06-16 00:00:00' '2016-11-22 00:00:00'
 '2017-07-05 00:00:00' '2016-09-13 00:00:00' '2017-03-13 00:00:00'
 '2017-01-03 00:00:00' '2017-01-04 00:00:00' '2017-01-18 00:00:00'
 '2017-05-18 00:00:00' '2017-05-30 00:00:00' '2017-01-10 00:00:00'
 '2017-08-11 00:00:00' '2017-08-02 00:00:00' '2017-07-28 00:00:00'
 '2017-06-15 00:00:00' '2017-08-22 00:00:00' '2016-09-02 00:00:00'
 '2017-02-03 00:00:00' '2017-04-06 00:00:00' '2017-02-07 00:00:00'
 '2017-05-26 00:00:00' '2017-08-10 00:00:00' '2017-01-24 00:00:00'
 '2016-12-26 00:00:00' '2017-08-18 00:00:00' '2017-02-13 00:00:00'
 '2016-09-30 00:00:00' '2017-04-12 00:00:00' '2017-05-09 00:00:00'
 '2016-10-29 00:00:00' '2017-02-27 00:00:00' '2017-01-01 00:00:00'
 '2017-06-01 00:00:00' '2016-10-03 00:00:00' '2017-08-15 00:00:00'
 '2016-12-12 00:00:00' '2016-12-17 00:00:00' '2017-08-03 00:00:00'
 '2016-09-22 00:00:00' '2016-12-31 00:00:00' '2016-10-04 00:00:00'
 '2016-09-20 00:00:00' '2017-03-21 00:00:00' '2017-08-08 00:00:00'
 '2017-04-05 00:00:00' '2017-08-16 00:00:00' '2017-02-22 00:00:00'
 '2017-02-04 00:00:00' '2017-05-16 00:00:00' '2017-03-24 00:00:00'
 '2017-03-09 00:00:00' '2017-07-21 00:00:00' '2017-04-04 00:00:00'
 '2016-09-19 00:00:00' '2017-01-07 00:00:00' '2016-10-21 00:00:00'
 '2017-04-29 00:00:00' '2017-07-22 00:00:00' '2017-02-20 00:00:00'
 '2016-10-23 00:00:00' '2017-01-02 00:00:00' '2016-10-12 00:00:00'
 '2017-07-15 00:00:00' '2016-10-16 00:00:00' '2017-03-14 00:00:00'
 '2017-04-30 00:00:00' '2017-04-09 00:00:00' '2017-03-04 00:00:00'
 '2016-09-17 00:00:00' '2017-06-03 00:00:00' '2017-05-06 00:00:00'
 '2017-07-03 00:00:00' '2017-01-28 00:00:00' '2017-03-05 00:00:00'
 '2016-11-27 00:00:00' '2017-02-11 00:00:00' '2017-06-24 00:00:00'
 '2017-01-21 00:00:00' '2016-10-22 00:00:00' '2016-10-10 00:00:00'
 '2016-11-05 00:00:00' '2017-05-20 00:00:00' '2017-08-06 00:00:00'

In [4]:
#didn't come up in the null because there is space.

#### #1 The "Ease-ment" column is empty. This was not counted originally in the count of nulls, because there is a space in each cell. With the unique values, this issue came up as the only unique value was a space. In the following cell I remove the entire column from the data set.

In [5]:
import numpy as np

# 1. Drop empty column
df.drop(columns=['EASE-MENT'], inplace=True)

#### #2 Another important change is the date column. As seen in the output of the .info function, the dates are stored as objects. The code bellow makes the dates into real values in time.

In [6]:
# Convert 'SALE DATE' to datetime objects
df['SALE DATE'] = pd.to_datetime(df['SALE DATE'])

# Verify the transformation
print(df['SALE DATE'].dtype)

datetime64[ns]

#### #3 Another change that I made is that an index column is automatically created for the data set. This data set comes already with an index column. The code below drops the index column and uses the column named "unnamed" as the index instead.

In [7]:
# Drop the column (replace 'Unnamed: 0' with the actual name if it has one)
df = df.drop(columns=['Unnamed: 0'])

# Optional: Reset the internal index so it starts at 0
df = df.reset_index(drop=True)

In [8]:
#printing the first few rows to ensure the changes worked.
df.head()

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,BUILDING CLASS AT PRESENT,ADDRESS,APARTMENT NUMBER,ZIP CODE,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
0,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,392,6,C2,153 AVENUE B,,10009,5,0,5,1633,6440,1900,2,C2,6625000,2017-07-19
1,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,26,C7,234 EAST 4TH STREET,,10009,28,3,31,4616,18690,1900,2,C7,-,2016-12-14
2,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,39,C7,197 EAST 3RD STREET,,10009,16,1,17,2212,7803,1900,2,C7,-,2016-12-09
3,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,402,21,C4,154 EAST 7TH STREET,,10009,10,0,10,2272,6794,1913,2,C4,3936272,2016-09-23
4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,404,55,C2,301 EAST 10TH STREET,,10009,6,0,6,2369,4615,1900,2,C2,8000000,2016-11-17

#### #4 In the unique values I noticed 0 as a value in the "zip code" column, as well as the "year built" column. It is impossible for the values to actually be 0. I changed all the 0 cells to NaN. I took the count to see how often the issue comes up.

In [9]:
import numpy as np

# Define the columns containing 0 as a placeholder
cols_with_zero = ['ZIP CODE', 'YEAR BUILT']

# Replace 0 with NaN
df[cols_with_zero] = df[cols_with_zero].replace(0, np.nan)

# Verification: Count how many NaNs are now in these columns
print(df[cols_with_zero].isnull().sum())

ZIP CODE       982
YEAR BUILT    6970
dtype: int64

#### #5 Out of the 84,547 rows of data, 982 is only about 1% and it would distort the data very much to make up zip codes. I dropped the columns that were missing zip codes. The "year built" consists of about 8% of the data which is more significant. In order not to loose all the information from these entries I replaced the "NaN" cells with the average year of the rest of the data set. I double checked the count of rows to see if they were dropped.

In [10]:
# 1. Drop rows with missing Zip Codes
df = df.dropna(subset=['ZIP CODE'])

# 2. Fill missing Years with the Median
year_median = df['YEAR BUILT'].median()
df['YEAR BUILT'] = df['YEAR BUILT'].fillna(year_median)

# 3. Final count check
print(f"Final Rows: {df.shape[0]}")
print(f"Final Columns: {df.shape[1]}")

Final Rows: 83566
Final Columns: 20

#### Looking more closely for spelling mistakes. It is likely that any neighborhood that appears very few times is a spelling mistake and not a real neighborhood. I didn't find any mistakes.

In [11]:
# Check for inconsistencies in Neighborhood naming
print(df['NEIGHBORHOOD'].value_counts().tail(20))

NEIGHBORHOOD
NEPONSIT                     34
ARROCHAR-SHORE ACRES         33
LIVINGSTON                   33
CONCORD-FOX HILLS            28
NEW BRIGHTON-ST. GEORGE      27
EMERSON HILL                 20
JAMAICA BAY                  19
FLUSHING MEADOW PARK         16
ROSSVILLE-RICHMOND VALLEY    14
RICHMONDTOWN-LIGHTHS HILL    14
AIRPORT LA GUARDIA            8
BLOOMFIELD                    7
ROSSVILLE-PORT MOBIL          6
CO-OP CITY                    5
DONGAN HILLS-OLD TOWN         5
FRESH KILLS                   2
VAN CORTLANDT PARK            2
BRONX PARK                    1
CITY ISLAND-PELHAM STRIP      1
EAST RIVER                    1
Name: count, dtype: int64

#### #6 The 'LAND SQUARE FEET', 'GROSS SQUARE FEET', and 'SALE PRICE' columns are all numeric values but were stored as objects. I changed the numbers in the column to integers using the .to_numeric function.

In [12]:
# Convert these three to numeric, turning dashes or spaces into NaN
cols_to_fix = ['LAND SQUARE FEET', 'GROSS SQUARE FEET', 'SALE PRICE']

for col in cols_to_fix:
    df[col] = pd.to_numeric(df[col].replace(' -  ', np.nan), errors='coerce')

#### #7 Although the Tax class at the time of sale is a number, it is just a class label with a numeric name. The number doesn't have any real value and I don't want the computer to make calculations with it so I changed it into a string.

In [13]:
# Convert Tax Class from integer to string to reflect it is a category
df['TAX CLASS AT TIME OF SALE'] = df['TAX CLASS AT TIME OF SALE'].astype(str)

# Verify the change
print(df['TAX CLASS AT TIME OF SALE'].dtype)

object

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 83566 entries, 0 to 84547
Data columns (total 20 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   BOROUGH                         83566 non-null  int64
 1   NEIGHBORHOOD                    83566 non-null  object
 2   BUILDING CLASS CATEGORY         83566 non-null  object
 3   TAX CLASS AT PRESENT            83566 non-null  object
 4   BLOCK                           83566 non-null  int64
 5   LOT                             83566 non-null  int64
 6   BUILDING CLASS AT PRESENT       83566 non-null  object
 7   ADDRESS                         83566 non-null  object
 8   APARTMENT NUMBER                83566 non-null  object
 9   ZIP CODE                        83566 non-null  float64
 10  RESIDENTIAL UNITS               83566 non-null  int64
 11  COMMERCIAL UNITS                83566 non-null  int64
 12  TOTAL UNITS                     83566 non-null  int64
 13  LAND SQUARE FEET                57547 non-null  float64
 14  GROSS SQUARE FEET               56542 non-null  float64
 15  YEAR BUILT                      83566 non-null  float64
 16  TAX CLASS AT TIME OF SALE       83566 non-null  object
 17  BUILDING CLASS AT TIME OF SALE  83566 non-null  object
 18  SALE PRICE                      69209 non-null  float64
 19  SALE DATE                       83566 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(5), int64(6), object(8)
memory usage: 13.4+ MB

In [15]:
# Save the cleaned dataframe to a CSV file
# index=False prevents pandas from creating a new "Unnamed: 0" column
df.to_csv('NYC_Rolling_Sales_Cleaned.csv', index=False)

print("File saved successfully.")

File saved successfully.

#### The dataset I used, "Nyc-rolling-sales data," is a public dataset that was published by the New York City Department of Finance. This is a trustworthy enough source for me to rely on in terms of integrity. I acquired it very ethically, straight from the website. Regarding the ethical considerations of my data, as always, any distortions or changes can distort the truth and increase bias. I will review the changes made to my dataset and discuss the implications. 
#### The first change I made was to remove the "Ease-Ment" column. Every row was missing, so this obviously isn't usable information, and there was no issue with deleting it. A technical change changed the date column from an object to a datetime object. This is so the date can be chronologically ordered and used as intended. Another change to the column's data type was made to improve data accuracy: the tax class number was changed from a numeric value to a string. This is important so the model doesn't make an order or levels in the class and just keeps it as a numeric label. The "Land Square feet", "Gross Square Feet", and "Sale Price" columns were all converted to integers so they can be calculated. 
#### The biggest ethical risk was handling missing values in the "Year Built" and "Zip Code" columns. In the zip code column, I removed those rows because entering new false zip codes would have further distorted the data, and they accounted for only 1% of the data. The issue now is that it is possible there is a pattern or reason the zip code was left out; maybe lower-income households have a harder time keeping accurate records, and removing all those entries makes the class very underrepresented. All empty cells in the year-built column were set to the average year of sale for the other houses in the dataset. This is good because I did not remove the affected entries, so as not to lose the rest of the information. The problem with using the average is that, if the analysis is a time-series model, the middle year would be grossly inaccurate. For a prediction model with the year as just one of the variables, it is okay to set the year to the median so the other variables can be used. Another issue is that most of the houses that are missing a year may have been sold a very long time ago. In that case, the old houses are extremely underrepresented. What I could do to go the extra mile and maintain a very high level of integrity is to document clearly that the year-average was substituted for empty values. As for the zip code, I can cross-reference the block and lot numbers with a secondary city database to find it.
####  Some Legal Guidelines include the Fair Housing Act, which means I can’t use the data for discrimination, and the Privacy Protections rules, which means I have to do more cleaning to remove any identifying information to protect the privacy of the people in the dataset.

Documentation:
I used gemini to get snippets of code. I wrote all the markdown cells and observations by myself.